# Exemplo de classificação com a base IRIS

In [23]:
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import cohen_kappa_score

In [24]:
dados = pd.read_csv("iris.csv")

In [25]:
dados.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

#### Caso queira substituir o valor de algum atributo categorico por numeros

In [26]:
#dados.loc[dados['species'] == 'setosa','species'] = 0
#dados.loc[dados['species'] == 'versicolor','species'] = 1
#dados.loc[dados['species'] == 'virginica','species'] = 2

In [27]:
#Pegando os atributos sem os labels
X = dados.iloc[:,0:-1]

In [28]:
Y = dados.iloc[:,-1]

In [29]:
X_treino, X_teste, Y_treino, Y_teste = train_test_split(X,Y,test_size=0.3)

In [30]:
#Quantidade de exemplos de cada classe no conjunto de treino
Y_treino.value_counts()

setosa        37
versicolor    34
virginica     34
Name: species, dtype: int64

In [31]:
MLP = MLPClassifier(hidden_layer_sizes=(10,10),max_iter=500)

MLP.fit(X_treino,Y_treino)
Y_predito = MLP.predict(X_teste)
matriz_confusao = confusion_matrix(Y_predito,Y_teste)
acuracia = accuracy_score(Y_predito,Y_teste)
kappa = cohen_kappa_score(Y_predito,Y_teste)

print(matriz_confusao)
print('Acurácia = ', acuracia)
print('Kappa = ', kappa)

[[13  0  0]
 [ 0 15  0]
 [ 0  1 16]]
Acurácia =  0.9777777777777777
Kappa =  0.9665178571428571


/Users/flavio/anaconda3/lib/python3.5/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


# Exemplo de classificação com a base pima-indians-diabetes

In [34]:
dados = pd.read_csv('pima-indians-diabetes.csv')

In [36]:
dados.head()

# 1. Number of times pregnant  \
0                              6   
1                              1   
2                              8   
3                              1   
4                              0   

   # 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                                148                               
1                                                 85                               
2                                                183                               
3                                                 89                               
4                                                137                               

   # 3. Diastolic blood pressure (mm Hg)  \
0                                     72   
1                                     66   
2                                     64   
3                                     66   
4                                     40   

   # 4. Triceps skin fold thickness (mm)  # 5. 2-Hour serum insulin (mu U/ml)  \
0                                     35                                    0   
1                                     29                                    0   
2                                      0                                    0   
3                                     23                                   94   
4                                     35                                  168   

   # 6. Body mass index (weight in kg/(height in m)^2)  \
0                                               33.6     
1                                               26.6     
2                                               23.3     
3                                               28.1     
4                                               43.1     

   # 7. Diabetes pedigree function  # 8. Age (years)  \
0                            0.627                50   
1                            0.351                31   
2                            0.672                32   
3                            0.167                21   
4                            2.288                33   

   # 9. Class variable (0 or 1)  
0                             1  
1                             0  
2                             1  
3                             0  
4                             1

In [37]:
#Contando o número de exemplos de cada classe
dados.iloc[:,-1].value_counts()

0    500
1    268
Name: # 9. Class variable (0 or 1), dtype: int64

In [38]:
X = dados.iloc[:,0:-1]

In [39]:
Y = dados.iloc[:,-1]

In [40]:
X_treino, X_teste, Y_treino, Y_teste = train_test_split(X,Y,test_size=0.3,stratify=Y)

In [41]:
Y_teste.value_counts()

0    150
1     81
Name: # 9. Class variable (0 or 1), dtype: int64

In [42]:
MLP = MLPClassifier(hidden_layer_sizes=(10,10),max_iter=500)

MLP.fit(X_treino,Y_treino)
Y_predito = MLP.predict(X_teste)
matriz_confusao = confusion_matrix(Y_predito,Y_teste)
acuracia = accuracy_score(Y_predito,Y_teste)
kappa = cohen_kappa_score(Y_predito,Y_teste)

print(matriz_confusao)
print('Acurácia = ', acuracia)
print('Kappa = ', kappa)

[[110  43]
 [ 40  38]]
Acurácia =  0.6406926406926406
Kappa =  0.20420869132113062
